{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ .Values.redis.fullnameOverride }}
    {{- include "pdf-to-podcast.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.redis.fullnameOverride }}
  type: {{ include "pdf-to-podcast.serviceType" . }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
{{- end }}
